export const emojisDisponibles = [
    { id: 1, name: 'Angry', source: require('../../assets/EMOJI/Angry Emoji.mp4') },
    { id: 2, name: 'Baby', source: require('../../assets/EMOJI/Baby Emoji.mp4') },
    { id: 3, name: 'Beaming Face', source: require('../../assets/EMOJI/Beaming Face Emoji.mp4') },
    { id: 4, name: 'Chill Face', source: require('../../assets/EMOJI/Chill Face Emoji.mp4') },
    { id: 5, name: 'Clapping Hands', source: require('../../assets/EMOJI/Clapping Hands Emoji.mp4') },
    { id: 6, name: 'Cold Face', source: require('../../assets/EMOJI/Cold Face Emoji.mp4') },
    { id: 7, name: 'Cool', source: require('../../assets/EMOJI/Cool Emoji.mp4') },
    { id: 8, name: 'Crown Splash', source: require('../../assets/EMOJI/Crown Emoji Splash.mp4') },
    { id: 9, name: 'Crying', source: require('../../assets/EMOJI/Crying Emoji.mp4') },
    { id: 10, name: 'Crying Face', source: require('../../assets/EMOJI/Crying Face Emoji.mp4') },
    { id: 11, name: 'Devil Face', source: require('../../assets/EMOJI/Devil Face Emoji.mp4') },
    { id: 12, name: 'Driving Face', source: require('../../assets/EMOJI/Driving Face Emoji.mp4') },
    { id: 13, name: 'Thinking', source: require('../../assets/EMOJI/Emoji Thinking.mp4') },
    { id: 14, name: 'Eyes', source: require('../../assets/EMOJI/Eyes emoji.mp4') },
    { id: 15, name: 'Blowing Kiss', source: require('../../assets/EMOJI/Face Blowing A Kiss Emoji.mp4') },
    { id: 16, name: 'Holding Back Tears', source: require('../../assets/EMOJI/Face Holding Back Tears Emoji.mp4') },
    { id: 17, name: 'Fake Smile', source: require('../../assets/EMOJI/Fake Smile Emoji.mp4') },
    { id: 18, name: 'Fearful Face', source: require('../../assets/EMOJI/Fearful Face Emoji.mp4') },
    { id: 19, name: 'Flexed Biceps', source: require('../../assets/EMOJI/Flexed Biceps Emoji.mp4') },
    { id: 20, name: 'Funny', source: require('../../assets/EMOJI/Funny Emoji.mp4') },
    { id: 21, name: 'Grinning Face', source: require('../../assets/EMOJI/Grinning Face.mp4') },
    { id: 22, name: 'Happy Face', source: require('../../assets/EMOJI/Happy Face Emoji.mp4') },
    { id: 23, name: 'Headphones', source: require('../../assets/EMOJI/Headphones Emoji.mp4') },
    { id: 24, name: 'Hi Face', source: require('../../assets/EMOJI/Hi Face Emoji.mp4') },
    { id: 25, name: 'House Face', source: require('../../assets/EMOJI/House Face Emoji.mp4') },
    { id: 26, name: 'Kiss Face', source: require('../../assets/EMOJI/Kiss Face Emoji.mp4') },
    { id: 27, name: 'Kiss Mark Splash', source: require('../../assets/EMOJI/Kiss Mark Emoji Splash.mp4') },
    { id: 28, name: 'Knife', source: require('../../assets/EMOJI/Knife Emoji.mp4') },
    { id: 29, name: 'Laughing Face', source: require('../../assets/EMOJI/Laughing Face Emoji.mp4') },
    { id: 30, name: 'Liar Face', source: require('../../assets/EMOJI/Liar Face Emoji.mp4') },
    { id: 31, name: 'Lifting Face', source: require('../../assets/EMOJI/Lifiting Face Emoji.mp4') },
    { id: 32, name: 'Money', source: require('../../assets/EMOJI/Money Emoji.mp4') },
    { id: 33, name: 'Muscle', source: require('../../assets/EMOJI/Muscle Emoji.mp4') },
    { id: 34, name: 'No Face', source: require('../../assets/EMOJI/No Face Emoji.mp4') },
    { id: 35, name: 'Rose Face', source: require('../../assets/EMOJI/Rose Face Emoji.mp4') },
    { id: 36, name: 'Sad', source: require('../../assets/EMOJI/Sad Emoji.mp4') },
    { id: 37, name: 'Sad Puppy Eyes', source: require('../../assets/EMOJI/Sad Puppy Eyes Emoji.mp4') },
    { id: 38, name: 'Smiling Hearts', source: require('../../assets/EMOJI/Smiling Face with Hearts Emoji.mp4') },
    { id: 39, name: 'Smiling Sunglasses', source: require('../../assets/EMOJI/Smiling Face with Sunglasses Emoji.mp4') },
    { id: 40, name: 'Squinting Tongue', source: require('../../assets/EMOJI/Squinting Face with Tongue Emoji.mp4') },
    { id: 41, name: 'Star Struck', source: require('../../assets/EMOJI/Star Struck Emoji.mp4') },
    { id: 42, name: 'Tongue Face', source: require('../../assets/EMOJI/Tongue Face Emoji.mp4') },
    { id: 43, name: 'Upset', source: require('../../assets/EMOJI/Upset Emoji.mp4') },
    { id: 44, name: 'Yoga Face', source: require('../../assets/EMOJI/Yoga Face Emoji.mp4') },
];

export const getEmojiSource = (name) => {
    const emoji = emojisDisponibles.find(e => e.name === name);
    return emoji ? emoji.source : null;
};
